# Site settings
title: Özel Bau GmbH
email: info@oezel-bau-gmbh.de
description: > # this means to ignore newlines until "baseurl:"
  Özel Bau GmbH, Oezel Bau GmbH, Bekir Özel, Bekir Oezel, WDVS, 
  Innen- und Außenputz, Fugenarbeiten aller Art, 
  Spachtelarbeiten, Malerarbeiten, Armierung, Reibeputz
baseurl: "/www_oezel-bau-gmbh_de/" # the subpath of your site, e.g. /blog/
url: "http://www-oezel-bau-gmbh-de-nuesschen" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
